simulation_plaqueEnTension: plaqueEnTension.py
	conda run --live-stream -n MS207 python plaqueEnTension.py

simulation_plaqueEnTensionMFS103: plaqueEnTensionMFS103.py
	conda run --live-stream -n MS207 python plaqueEnTensionMFS103.py

